#!/bin/bash
set -euo pipefail

# Env vars injected by docker-compose: POSTGRES_APP_USER, POSTGRES_APP_PASSWORD, POSTGRES_DB
APP_USER="${POSTGRES_APP_USER:-contexthub_app}"
APP_PASS="${POSTGRES_APP_PASSWORD:?POSTGRES_APP_PASSWORD must be set}"
MAIN_DB="${POSTGRES_DB:-contexthub}"
TEST_DB="${MAIN_DB}_test"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$MAIN_DB" <<-EOSQL
    -- Create application role (idempotent)
    DO \$\$
    BEGIN
        IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$APP_USER') THEN
            CREATE ROLE $APP_USER WITH LOGIN PASSWORD '$APP_PASS';
        END IF;
    END
    \$\$;

    -- Runtime privileges (CRUD only — no DDL)
    GRANT CONNECT ON DATABASE $MAIN_DB TO $APP_USER;
    GRANT USAGE ON SCHEMA public TO $APP_USER;
    ALTER DEFAULT PRIVILEGES FOR ROLE $POSTGRES_USER IN SCHEMA public
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $APP_USER;
    ALTER DEFAULT PRIVILEGES FOR ROLE $POSTGRES_USER IN SCHEMA public
        GRANT USAGE, SELECT ON SEQUENCES TO $APP_USER;
EOSQL

# Create test database
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE $TEST_DB;
    GRANT CONNECT ON DATABASE $TEST_DB TO $APP_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$TEST_DB" <<-EOSQL
    GRANT USAGE ON SCHEMA public TO $APP_USER;
    ALTER DEFAULT PRIVILEGES FOR ROLE $POSTGRES_USER IN SCHEMA public
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $APP_USER;
    ALTER DEFAULT PRIVILEGES FOR ROLE $POSTGRES_USER IN SCHEMA public
        GRANT USAGE, SELECT ON SEQUENCES TO $APP_USER;
EOSQL
